# Generated by Django 5.0.3 on 2024-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('clothtype', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Upcycle Nepal - Revive, Chittadhar Marg, Bangemuddha, Kathmandu 44600', 'Upcycle Nepal - Revive, Chittadhar Marg, Bangemuddha, Kathmandu 44600'), ('Public Cloth bank, M8HJ+QR4, Unnamed Road, Kathmandu 44600', 'Public Cloth bank, M8HJ+QR4, Unnamed Road, Kathmandu 44600'), ('Clothes Bank Sherpa (Thrift Clothes Shop), P9CC+548, Gokarneshwor 44600', 'Clothes Bank Sherpa (Thrift Clothes Shop), P9CC+548, Gokarneshwor 44600'), ('Sukhawati Charity Store, Kathmandu 44600', 'Sukhawati Charity Store, Kathmandu 44600'), ('Sukhawati Store, P7CR+GWJ, Kathmandu 44600', 'Sukhawati Store, P7CR+GWJ, Kathmandu 44600'), ('Action Works Nepal, Kathmandu 44600', 'Action Works Nepal, Kathmandu 44600'), ('Aroan Nepal - KC Complex, Second Floor, Kathmandu 44600', 'Aroan Nepal - KC Complex, Second Floor, Kathmandu 44600')], max_length=255)),
            ],
        ),
    ]
