# Generated by Django 5.0.3 on 2024-04-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='location',
        ),
        migrations.AddField(
            model_name='donation',
            name='bankLocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='banks.banklocation'),
            preserve_default=False,
        ),
    ]
