# Generated by Django 5.0.3 on 2024-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='clothbank',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
