# Generated by Django 5.0.3 on 2024-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_clothbank_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothbank',
            name='total_numberOfclothes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothbank',
            name='total_numberOfdonations',
            field=models.IntegerField(default=0),
        ),
    ]
