# Generated by Django 5.0.3 on 2024-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_donation_location_donation_banklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='clothtype',
            field=models.CharField(choices=[('SHIRT', 'Shirt'), ('TROUSERS', 'Trousers'), ('DRESS', 'Dress'), ('COAT', 'Coat'), ('SWEATER', 'Sweater'), ('SKIRT', 'Skirt'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
