# Generated by Django 5.0.3 on 2024-04-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_status_alter_clothbank_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothbank',
            name='map_url',
            field=models.CharField(default='hello', max_length=512),
        ),
    ]
