# Generated by Django 5.0.3 on 2024-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('CLOTHBANKADMIN', 'Clothbankadmin')], default='DONOR', max_length=20),
        ),
    ]
